### ISSUE TITLE
Create Seed For Skills and Interest

### ISSUE THREAD

**Issue by seanmarcia** [rubyforgood/CharterForCompassion#34]
Reed (the stakeholder) sent me the definitive list. We need to create a seed file or another strategy for loading them :)

#### Skills

educator
curriculum designer
editor – print
editor – film
journalist - writer
filmmaker
accountant
business acumen
organizational coordinator
graphic arts
animator
mentoring
grassroots organizing
IT
IT - Joomla
IT – civicCRM
social media
administration
marketing
e-commerce
fundraising
public speaking
facilitation
 
 
#### Interests
arts
aging and elder issues
healthcare
education
business
environment
peace
restorative justice
social justice
social services
science and research
religion/interfaith/spirituality
women and girls
youth

**Comment by keithrbennett** [comment]
Submitted PR #36.

**Comment by keithrbennett** [comment]
@seanmarcia The skills were not in any apparent order, so I sorted them in dictionary order before copying them to the source code.
