### ISSUE TITLE
Admin user can add, remove and update Interests

### ISSUE THREAD

**Issue by mobjohnson** [rubyforgood/CharterForCompassion#46]
Amanda is the website Administrator.

**Comment by rossfuhrman** [comment]
This issue is dependent on #65 being done first.

**Comment by rossfuhrman** [comment]
From time to time, the list of Interests will need to be updated and and there is currently no way for Interests to be managed.

**Comment by ElishebaW** [comment]
Grabbing this one.

**Comment by ElishebaW** [comment]
I'm taking this!

**Comment by mobjohnson** [comment]
@ElishebaW on the github screen for this issue above and to the right, click Assignees to assign yourself, so no one else grabs it. And thanks for your help!!! :)
