### ISSUE TITLE
Landing page should provide context and instructions

### ISSUE THREAD

**Issue by mobjohnson** [rubyforgood/CharterForCompassion#47]
The front page needs to be redesigned to give a clearer understanding of the purpose of the application and how it is used.
There is not enough information on the landing page for new users on how to use the site. The owner will provide the content for the page as well as additional static pages (about, contact, faq, etc) to be implemented.
Includes replacing the word Logo with the Charter logo.
Remove the YouTube video as this increases loading time.

**Comment by mobjohnson** [comment]
info provided by Reed:
Here's some text for the front page This is the Charter for Compassion's connection portal – Compassion Connect. 
Enter information about yourself and your organization here, and be easily connected with other people and groups that share your interests or have skills or expertise you need to advance your work.

Start out by entering your information and then search – you can filter searches by interests, skills, and geography. 
If you have questions, you can send them to contact@charterforcompassion.org

This app was created by Ruby for Good volunteers as a gift to the Charter. We appreciate their support. rubyforgood.org

**Comment by mobjohnson** [comment]
![image](https://user-images.githubusercontent.com/7301882/29638794-596dcc84-8826-11e7-8193-2dfc048da584.png)

**Comment by rossfuhrman** [comment]
We need the image @mobjohnson attached to the issue to also be included on the front page.
