### ISSUE TITLE
Individual user can email an Organization and the site Admin in the app

### ISSUE THREAD

**Issue by mobjohnson** [rubyforgood/CharterForCompassion#50]
Amanda is the website Administrator.
Olivia is the Organization representative.
Irene is the interested Individual.  After a search, she clicks a Contact link next to the Organization's info in the list. She can also click a Contact link for Charter.

**Comment by rossfuhrman** [comment]
Rewording the notes mobjohnson provided:
Irene is an interested Individual. After a search, she clicks a Contact link next to the Organization's info in the list and this allows her to send an email to the Organization. She can also click a Contact link for Charter to send an email to the site admins

**Comment by ElishebaW** [comment]
@rossfuhrman @mobjohnson  Is this what you were thinking with this issue? The fonts and styles will match the current CSS in the app of course. Just wanted to get confirmation on what you were looking for using a quick mockup :)

![mockup](https://user-images.githubusercontent.com/20779752/31642129-5b58c31c-b2b7-11e7-8d46-7075feb6de1b.jpg)

**Comment by ElishebaW** [comment]
I'll take this one!

**Comment by rossfuhrman** [comment]
@ElishebaW Yes, that screenshot looks good to me. Thank you for your help!
On the mockup, each of the organizations have only one website listed. But IIRC, an organization can have two websites tied to their organization, one that is the URL for their site, like the ones you have mocked up, but they also may have the URL to their page on the Charter for Compassion site listed. They may have one or the other, both, or none.
