### ISSUE TITLE
Irene can provide international addresses on signup

### ISSUE THREAD

**Issue by mobjohnson** [rubyforgood/CharterForCompassion#52]
Issue reported from user in UK. Addresses there require more that the three fields that we provide,

**Comment by rossfuhrman** [comment]
A user should be able to enter an Address 2 and Address 3 line for their address.
We would also need to update any place we display this.
I think this is a good reference for more info: https://www.alliescomputing.com/support/how-to-build-a-uk-address-form

**Comment by rossfuhrman** [comment]
I should clarify, I think we'd want to take approach 2).

**Comment by smurfik** [comment]
I'll work on this one :)

**Comment by rossfuhrman** [comment]
Thanks, I will remove the `help wanted` label.
