### ISSUE TITLE
Olivia can edit her Organization info

### ISSUE THREAD

**Issue by mobjohnson** [rubyforgood/CharterForCompassion#53]
Olivia is the Organization representative.

**Comment by rossfuhrman** [comment]
For this issue, we just want the ability for a user to edit info about an Organization that they are in.
We have the ability to add an Organization, and view details about an Organization, but now we want to be able to edit it.

The ability to restrict editing to just Organization representatives, as opposed to Organization members, will be handled in a separate issue as we do not currently have code to handle the difference between a Organization representative and an Organization member.

![screenshot_10_1_17__9_48_am](https://user-images.githubusercontent.com/343188/31055789-cd158700-a68d-11e7-9f5d-f8f9cd097ddc.png)

**Comment by smurfik** [comment]
it looks like Edit functionality is already in the app -- I just added a link to the show page and an 'update' route
