### ISSUE TITLE
When setting up and Organization, the user can provide an international address

### ISSUE THREAD

**Issue by rossfuhrman** [rubyforgood/CharterForCompassion#62]
A user should be able to enter an Address 2 and Address 3 line for the address of an organization.
We would also need to update any place we display this.
I think this is a good reference for more info: https://www.alliescomputing.com/support/how-to-build-a-uk-address-form

**Comment by rossfuhrman** [comment]
I should clarify, I think we'd want to take approach 2).

**Comment by zluo16** [comment]
Hey! I think I can take a look at that!

**Comment by rossfuhrman** [comment]
Thanks, I will remove the `help wanted` label.

**Comment by rossfuhrman** [comment]
@zluo16 Any luck on this? Please let us know if you have any questions.

**Comment by rossfuhrman** [comment]
@zluo16 If you are working on this please let us know.
That being said, I think we can consider this issue as available for anyone that would like to tackle it. Thanks.
