### ISSUE TITLE
User Edit Profile form checkbox shows incorrectly

### ISSUE THREAD

**Issue by rossfuhrman** [rubyforgood/CharterForCompassion#64]
The checkbox for the :private field labeled "Show my name in search results" is behaving the opposite of how it should. When the field is set to true (meaning it should be private), the checkbox in the form is checked (meaning it should be public). The checkbox behaviour needs to be changed so that it matches the state of the data.
You can duplicate this by going to http://localhost:3000/users/edit and comparing the checkbox to the value in the :private column for the given user.
I imagine the same thing is happening when creating a new user and should also be checked and fixed as needed.

**Comment by Sey1000** [comment]
I think.. I'm just going to change the text to "Hide my name from search results" because if the default is public (private: false), then a user action (=checking the box) should change the state away from the default. Working on this now
