### ISSUE TITLE
Change login text above password input fields

### ISSUE THREAD

**Issue by mobjohnson** [rubyforgood/CharterForCompassion#78]
Change the language in the login screen. To"Change Password (leave blank if you don't want to change it)" and "New Password Confirmation (leave blank if you don't want to change it)"

![charter log in](https://user-images.githubusercontent.com/7301882/31695068-188194b4-b376-11e7-9d1c-bea44af36c57.JPG)

**Comment by swdonovan** [comment]
Hi @mobjohnson I am new to contributing to open source issues and was wondering if I could pick up this issue and help out quick? If someone has already fixed it, I can help with something else if theres anything available!
Thank you!

**Comment by mcshakes** [comment]
If no one called dibs on this, I'd be happy to get it out of the way.

**Comment by mobjohnson** [comment]
@mcshakes Go for it!

**Comment by mobjohnson** [comment]
Thanks for your help on this!
