### ISSUE TITLE
Add and edit skills

### ISSUE THREAD

**Issue by mobjohnson** [rubyforgood/CharterForCompassion#79]
Add Musician as a skill
Note on the drop down skill list -- "IT-CivicCRM" should be "IT-CiviCRM"
Also add Technology in the interest drop down

**Comment by admir23** [comment]
Hi @mobjohnson , is it ok if I work on this? Thanks :)

**Comment by mobjohnson** [comment]
Hi @admir23 , yes, please do so!!! and click the 'assign yourself' under Assignees at the top right. Thanks!!!

**Comment by admir23** [comment]
Thanks @mobjohnson 
The assign button is not available , I think you need to send me an invite first?

**Comment by mobjohnson** [comment]
@admir23 I was wrong about you being able to assign yourself. I am not sure how to invite you into the group that can do this, but thanks for you help!

**Comment by smurfik** [comment]
#83 closes issue #79
